{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdm.api",
    "module": "emcloudy_sdk",
    "version": "1.0-20250731093342",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 22,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "emcloudy_sdk-1.0-20250731093342.jar",
          "url": "emcloudy_sdk-1.0-20250731093342.jar",
          "size": 13772,
          "sha512": "b301c3d446014dd3eeb020be7709e737e0f78a99a0edd5a7b1c07692a5d61cdde3a8a12e97bdee72e236667898f0d15ade4ea571b0f44a005a02d034cfd18eae",
          "sha256": "aaf4c4727f7b17e722d523bdaa0f080a8a30f60008703318f7f84e3ba8ac039a",
          "sha1": "9a6f71c9d9b751dccbde8ff2463a40912e68ee33",
          "md5": "e94825230d0b100bbc4cac95b2b79773"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 22,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "emcloudy_sdk-1.0-20250731093342.jar",
          "url": "emcloudy_sdk-1.0-20250731093342.jar",
          "size": 13772,
          "sha512": "b301c3d446014dd3eeb020be7709e737e0f78a99a0edd5a7b1c07692a5d61cdde3a8a12e97bdee72e236667898f0d15ade4ea571b0f44a005a02d034cfd18eae",
          "sha256": "aaf4c4727f7b17e722d523bdaa0f080a8a30f60008703318f7f84e3ba8ac039a",
          "sha1": "9a6f71c9d9b751dccbde8ff2463a40912e68ee33",
          "md5": "e94825230d0b100bbc4cac95b2b79773"
        }
      ]
    }
  ]
}
